### ISSUE TITLE
Asserts

### ISSUE THREAD

**Issue by snowthesprite** [charliebrown364/graph#1]
Hey Charlie, you either REALLY need to assert, or the problem I had is more common than I thought. If you are asserting and you know you are, check your repl.it. If the assert boxes don't have the git hub logo appear when you hover over them, its not actually pushing the data up to git hub.  Your gonna have to make a new repl.it repository connected to this backup to get it to work again. I know how to make the asserts work if they just won't happen at all either, so ask if thats the problem.

**Comment by charliebrown364** [comment]
Not sure why that happened last month. It works now.
